#!/usr/bin/env node
/* =========================================================================
   build-single.js — bundle the whole game into one self-contained .html
   file with the stylesheet, three.js and every script inlined.

     node build-single.js            ->  laststand.html
     node build-single.js out.html   ->  out.html

   The output has no external references at all, so it can be emailed,
   dropped on a USB stick, or opened straight off the desktop.
   ========================================================================= */
const fs = require('fs');
const path = require('path');

const root = __dirname;
const out = path.resolve(root, process.argv[2] || 'laststand.html');

const read = f => fs.readFileSync(path.join(root, f), 'utf8');

/* A literal </script> inside inlined JS would close the tag early. */
const safe = js => js.replace(/<\/script/gi, '<\\/script');

let html = read('index.html');

/* 1. stylesheet -> <style> */
html = html.replace(
  /<link rel="stylesheet" href="([^"]+)">/g,
  (_, href) => '<style>\n' + read(href).trim() + '\n</style>'
);

/* 2. every <script src="..."> -> inline <script>, in document order */
const inlined = [];
html = html.replace(
  /[ \t]*<script src="([^"]+)"><\/script>\n?/g,
  (_, src) => {
    inlined.push(src);
    return '<script>\n/* ---- ' + src + ' ---- */\n' + safe(read(src).trim()) + '\n</script>\n';
  }
);

if (!inlined.length) {
  console.error('build-single: found no <script src> tags in index.html — nothing to inline.');
  process.exit(1);
}

/* 3. a banner so the file explains itself when someone opens it in an editor */
html = html.replace('<head>', `<head>
<!--
  Last Stand — 3D Tower Defense.  SINGLE-FILE BUILD.

  Generated by build-single.js from the sources in this repository; edit
  those and re-run the script rather than editing this file by hand.
  Everything is inlined, so this works offline and straight from file://.

  Bundled: three.js r158 (c) three.js authors, MIT — see vendor/three.LICENSE
-->`);

fs.writeFileSync(out, html);

const kb = n => (n / 1024).toFixed(0) + ' KB';
console.log('wrote ' + path.relative(root, out) + '  (' + kb(Buffer.byteLength(html)) + ')');
inlined.forEach(f => console.log('  inlined ' + f.padEnd(24) + kb(Buffer.byteLength(read(f)))));
